# Permalinks
permalink:           pretty

# Setup
title:               Ryan Stroud
tagline:             Blog?
url:                 http://ryanstroud.github.io
paginate:            1
baseurl:             ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Ryan Stroud
  url:               https://twitter.com/ryanstroud
  email:             ryanstroud@gmail.com

# Custom vars
version:             2.0.0
github:
  repo:              https://github.com/poole/poole

# Gems
gems:
  - jekyll-paginate
  - jekyll-gist
